[project]
name = "scoop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hidpi-tk>=1.0.0",
    "pyinstaller>=6.14.0",
]
